version: '4'
services:
 frontend:
  build: ./frontend
  container_name: front_coleta
  ports:
   - "4200:4200"

 backend:
  build: ./backend
  container_name: back_coleta
  depends_on:
   redis:
    condition: service_started
  ports:
   - "8080:8080"

 redis:
  image: redis
  container_name: cache_coleta
  ports:
   - "6379:6379"